### ISSUE TITLE
UNRESOLVED DEPENDENCIES

### ISSUE THREAD

**Issue by shivamka1** [timt/sbt-npm#4]
I am getting this unresolved dependency. Please let me know, how could I fix this?

Sbt version# 1.2.7

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.shaka#sbt-npm;8: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		io.shaka:sbt-npm:8 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		io.shaka:sbt-npm:8 (scalaVersion=2.12, sbtVersion=1.0) (/home/shivam/glassbeam/repositories/gbnewplatform/project/plugins.sbt#L17-18)
[warn] 		  +- default:gbnewplatform-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: io.shaka#sbt-npm;8: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
```

**Comment by shivamka1** [comment]
When I tried to compile this project with sbt version# 1.2.7, I got follow up dependencies issues!

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.sbt#sbt-pgp;0.8.3: not found
[warn] 	:: me.lessis#bintray-sbt;0.3.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```
